### ISSUE TITLE
start_ingest.sh is failing to ingest data into hdfs from local path

### ISSUE THREAD

**Issue by saiganji** [01org/open-network-insight#5]
We are trying to ingest real time netflow data generated by nfcapd into hdfs using start_ingest.sh script but we are not seeing any new files being ingested into hdfs path: hdfs://user/duxbury/flow/

Could you guys help us fix the issue ? 

Our format of data in local collector path is:
"collector_path":"/mnt/sec_shared.nfs/nfcapd",
 Sample data file generated by nfcapd: 
/mnt/sec_shared.nfs/nfcapd/2016/01/21/07/nfcapd.2016012107

Status of ingest session:
==================
[duxbury@gateway ingest]$ ./start_ingest.sh flow 3
Background ingest session is running: OniIngest_flow_19_37_03
To rejoin the sessin use: session -x OniIngest_flow_19_37_03
[duxbury@gateway ingest]$ screen -x OniIngest_flow_19_37_03

Listening server 10.0.0.241, queue:flow_ingest_queue

Rabbitmq server log: successful connections from 3 workers
==============================================

=INFO REPORT==== 22-Jan-2016::00:31:51 ===
accepting AMQP connection <0.218.0> (10.0.0.241:50075 -> 10.0.0.241:5672)

=INFO REPORT==== 22-Jan-2016::00:31:51 ===
accepting AMQP connection <0.222.0> (10.0.0.241:50076 -> 10.0.0.241:5672)

=INFO REPORT==== 22-Jan-2016::00:31:51 ===
accepting AMQP connection <0.245.0> (10.0.0.241:50077 -> 10.0.0.241:5672)

- Sai Ganji
Cloudwick Team

**Comment by EverIntel** [comment]
Hi,
Can you  redirect the nfcapd files to the same path of the collector_path ? 

It will be something like:
 1. collector_path:**"/mnt/sec_shared.nfs/flow”,**
 2. File generated:**/mnt/sec_shared.nfs/flow/nfcapd.2016012107**

The  master ingest is looking for files in the collector_path , any time that a new file comes to that path (**/mnt/sec_shared.nfs/flow**), the master ingest takes the file and uploads it to HDFS , it is not necessary to have a path for different dates.

Regards
Ever

**Comment by saiganji** [comment]
Hello EverIntel, the collector_path in my comment was a typo. Sorry about that.

I was able to solve this issue temporarily by removing the path for different dates : /mnt/sec_shared.nfs/nfcapd/nfcapd.2016012107.

I am still troubleshooting it. Will get back to you by the end of the day. Thank you for your immediate response and help
